baseurl: https://pytips.netlify.app/
languageCode: en-us
title: Welcome to PyTips
theme: blackburn
author: Priyanga Dilini Talagala
copyright: '&copy; 2022. All rights reserved.'
canonifyurls: yes
paginate: 10
indexes:
  tag: tags
  topic: topics
params:
  brand: PyTips
  dateFormat: 02 Jan 2006, 15:04
  disqus: Your Disqus shortname
  googleAnalytics: Your Google Analytics tracking ID
  highlightjs: androidstudio
  subtitle: Data Analysis and Programming with Python Programming Language
menu:
  main:
    - identifier: home
      name: Home
      pre: <i class='fa fa-home fa-fw'></i>
      url: /
      weight: 1
    - identifier: post
      name: Posts
      pre: <i class='fa fa-list fa-fw'></i>
      url: /post/
      weight: 2
    - identifier: about
      name: About
      pre: <i class='fa fa-user fa-fw'></i>
      url: /about/
      weight: 3
    - name: Contact
      pre: <i class='fa fa-phone fa-fw'></i>
      url: /contact/
      weight: 4
social:
  #facebook: '*'
  github: pridiltal
  #instagram: '*'
  #linkedin: '*'
  #stackoverflow: '*'
  twitter: pridiltal
